[package]
name = "moneypenny"
version = "0.1.0"
authors = ["Tom Clayton <tom.clayton@stfc.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
